var annotated_dup =
[
    [ "std", null, [
      [ "hash< tz::Handle< T > >", "structstd_1_1hash_3_01tz_1_1_handle_3_01_t_01_4_01_4.html", null ]
    ] ],
    [ "tz", null, [
      [ "detail", null, [
        [ "CallbackType", "structtz_1_1detail_1_1_callback_type.html", null ]
      ] ],
      [ "gl", null, [
        [ "ogl2", null, [
          [ "Buffer", "classtz_1_1gl_1_1ogl2_1_1_buffer.html", "classtz_1_1gl_1_1ogl2_1_1_buffer" ],
          [ "BufferInfo", "structtz_1_1gl_1_1ogl2_1_1_buffer_info.html", "structtz_1_1gl_1_1ogl2_1_1_buffer_info" ],
          [ "FormatData", "structtz_1_1gl_1_1ogl2_1_1_format_data.html", null ],
          [ "Framebuffer", "classtz_1_1gl_1_1ogl2_1_1_framebuffer.html", "classtz_1_1gl_1_1ogl2_1_1_framebuffer" ],
          [ "FramebufferInfo", "structtz_1_1gl_1_1ogl2_1_1_framebuffer_info.html", "structtz_1_1gl_1_1ogl2_1_1_framebuffer_info" ],
          [ "Image", "classtz_1_1gl_1_1ogl2_1_1_image.html", "classtz_1_1gl_1_1ogl2_1_1_image" ],
          [ "ImageInfo", "structtz_1_1gl_1_1ogl2_1_1_image_info.html", "structtz_1_1gl_1_1ogl2_1_1_image_info" ],
          [ "Renderbuffer", "classtz_1_1gl_1_1ogl2_1_1_renderbuffer.html", null ],
          [ "RenderbufferInfo", "structtz_1_1gl_1_1ogl2_1_1_renderbuffer_info.html", "structtz_1_1gl_1_1ogl2_1_1_renderbuffer_info" ],
          [ "Sampler", "structtz_1_1gl_1_1ogl2_1_1_sampler.html", "structtz_1_1gl_1_1ogl2_1_1_sampler" ],
          [ "Shader", "classtz_1_1gl_1_1ogl2_1_1_shader.html", "classtz_1_1gl_1_1ogl2_1_1_shader" ],
          [ "ShaderInfo", "structtz_1_1gl_1_1ogl2_1_1_shader_info.html", "structtz_1_1gl_1_1ogl2_1_1_shader_info" ],
          [ "ShaderModule", "classtz_1_1gl_1_1ogl2_1_1_shader_module.html", "classtz_1_1gl_1_1ogl2_1_1_shader_module" ],
          [ "ShaderModuleInfo", "structtz_1_1gl_1_1ogl2_1_1_shader_module_info.html", "structtz_1_1gl_1_1ogl2_1_1_shader_module_info" ],
          [ "VertexArray", "classtz_1_1gl_1_1ogl2_1_1_vertex_array.html", "classtz_1_1gl_1_1ogl2_1_1_vertex_array" ]
        ] ],
        [ "vk2", null, [
          [ "detail", null, [
            [ "DeviceFeatureInfo", "structtz_1_1gl_1_1vk2_1_1detail_1_1_device_feature_info.html", null ]
          ] ],
          [ "hardware", null, [
            [ "Queue", "classtz_1_1gl_1_1vk2_1_1hardware_1_1_queue.html", "classtz_1_1gl_1_1vk2_1_1hardware_1_1_queue" ],
            [ "QueueInfo", "structtz_1_1gl_1_1vk2_1_1hardware_1_1_queue_info.html", null ]
          ] ],
          [ "Attachment", "structtz_1_1gl_1_1vk2_1_1_attachment.html", "structtz_1_1gl_1_1vk2_1_1_attachment" ],
          [ "BinarySemaphore", "classtz_1_1gl_1_1vk2_1_1_binary_semaphore.html", null ],
          [ "Buffer", "classtz_1_1gl_1_1vk2_1_1_buffer.html", "classtz_1_1gl_1_1vk2_1_1_buffer" ],
          [ "BufferInfo", "structtz_1_1gl_1_1vk2_1_1_buffer_info.html", "structtz_1_1gl_1_1vk2_1_1_buffer_info" ],
          [ "ColourBlendState", "structtz_1_1gl_1_1vk2_1_1_colour_blend_state.html", null ],
          [ "CommandBuffer", "classtz_1_1gl_1_1vk2_1_1_command_buffer.html", "classtz_1_1gl_1_1vk2_1_1_command_buffer" ],
          [ "CommandBufferRecording", "classtz_1_1gl_1_1vk2_1_1_command_buffer_recording.html", "classtz_1_1gl_1_1vk2_1_1_command_buffer_recording" ],
          [ "CommandPool", "classtz_1_1gl_1_1vk2_1_1_command_pool.html", "classtz_1_1gl_1_1vk2_1_1_command_pool" ],
          [ "CommandPoolInfo", "structtz_1_1gl_1_1vk2_1_1_command_pool_info.html", "structtz_1_1gl_1_1vk2_1_1_command_pool_info" ],
          [ "ComputePipeline", "classtz_1_1gl_1_1vk2_1_1_compute_pipeline.html", null ],
          [ "ComputePipelineInfo", "structtz_1_1gl_1_1vk2_1_1_compute_pipeline_info.html", null ],
          [ "DepthStencilState", "structtz_1_1gl_1_1vk2_1_1_depth_stencil_state.html", "structtz_1_1gl_1_1vk2_1_1_depth_stencil_state" ],
          [ "DescriptorLayout", "classtz_1_1gl_1_1vk2_1_1_descriptor_layout.html", "classtz_1_1gl_1_1vk2_1_1_descriptor_layout" ],
          [ "DescriptorLayoutBuilder", "classtz_1_1gl_1_1vk2_1_1_descriptor_layout_builder.html", "classtz_1_1gl_1_1vk2_1_1_descriptor_layout_builder" ],
          [ "DescriptorLayoutInfo", "structtz_1_1gl_1_1vk2_1_1_descriptor_layout_info.html", "structtz_1_1gl_1_1vk2_1_1_descriptor_layout_info" ],
          [ "DescriptorPool", "classtz_1_1gl_1_1vk2_1_1_descriptor_pool.html", "classtz_1_1gl_1_1vk2_1_1_descriptor_pool" ],
          [ "DescriptorPoolInfo", "structtz_1_1gl_1_1vk2_1_1_descriptor_pool_info.html", "structtz_1_1gl_1_1vk2_1_1_descriptor_pool_info" ],
          [ "DescriptorSet", "classtz_1_1gl_1_1vk2_1_1_descriptor_set.html", "classtz_1_1gl_1_1vk2_1_1_descriptor_set" ],
          [ "DynamicState", "structtz_1_1gl_1_1vk2_1_1_dynamic_state.html", null ],
          [ "Fence", "classtz_1_1gl_1_1vk2_1_1_fence.html", "classtz_1_1gl_1_1vk2_1_1_fence" ],
          [ "FenceInfo", "structtz_1_1gl_1_1vk2_1_1_fence_info.html", "structtz_1_1gl_1_1vk2_1_1_fence_info" ],
          [ "Framebuffer", "classtz_1_1gl_1_1vk2_1_1_framebuffer.html", "classtz_1_1gl_1_1vk2_1_1_framebuffer" ],
          [ "FramebufferInfo", "structtz_1_1gl_1_1vk2_1_1_framebuffer_info.html", "structtz_1_1gl_1_1vk2_1_1_framebuffer_info" ],
          [ "GraphicsPipeline", "classtz_1_1gl_1_1vk2_1_1_graphics_pipeline.html", null ],
          [ "GraphicsPipelineInfo", "structtz_1_1gl_1_1vk2_1_1_graphics_pipeline_info.html", "structtz_1_1gl_1_1vk2_1_1_graphics_pipeline_info" ],
          [ "Image", "classtz_1_1gl_1_1vk2_1_1_image.html", "classtz_1_1gl_1_1vk2_1_1_image" ],
          [ "ImageInfo", "structtz_1_1gl_1_1vk2_1_1_image_info.html", "structtz_1_1gl_1_1vk2_1_1_image_info" ],
          [ "ImageView", "classtz_1_1gl_1_1vk2_1_1_image_view.html", null ],
          [ "ImageViewInfo", "structtz_1_1gl_1_1vk2_1_1_image_view_info.html", null ],
          [ "LogicalDevice", "classtz_1_1gl_1_1vk2_1_1_logical_device.html", "classtz_1_1gl_1_1vk2_1_1_logical_device" ],
          [ "LogicalDeviceInfo", "structtz_1_1gl_1_1vk2_1_1_logical_device_info.html", "structtz_1_1gl_1_1vk2_1_1_logical_device_info" ],
          [ "MultisampleState", "structtz_1_1gl_1_1vk2_1_1_multisample_state.html", null ],
          [ "PhysicalDevice", "classtz_1_1gl_1_1vk2_1_1_physical_device.html", "classtz_1_1gl_1_1vk2_1_1_physical_device" ],
          [ "PhysicalDeviceInfo", "structtz_1_1gl_1_1vk2_1_1_physical_device_info.html", null ],
          [ "PhysicalDeviceSurfaceCapabilityInfo", "structtz_1_1gl_1_1vk2_1_1_physical_device_surface_capability_info.html", "structtz_1_1gl_1_1vk2_1_1_physical_device_surface_capability_info" ],
          [ "Pipeline", "classtz_1_1gl_1_1vk2_1_1_pipeline.html", null ],
          [ "PipelineLayout", "classtz_1_1gl_1_1vk2_1_1_pipeline_layout.html", null ],
          [ "PipelineLayoutInfo", "structtz_1_1gl_1_1vk2_1_1_pipeline_layout_info.html", "structtz_1_1gl_1_1vk2_1_1_pipeline_layout_info" ],
          [ "PipelineState", "structtz_1_1gl_1_1vk2_1_1_pipeline_state.html", null ],
          [ "QueueFamilyInfo", "structtz_1_1gl_1_1vk2_1_1_queue_family_info.html", null ],
          [ "QueueRequest", "structtz_1_1gl_1_1vk2_1_1_queue_request.html", "structtz_1_1gl_1_1vk2_1_1_queue_request" ],
          [ "QueueStorage", "classtz_1_1gl_1_1vk2_1_1_queue_storage.html", null ],
          [ "RasteriserState", "structtz_1_1gl_1_1vk2_1_1_rasteriser_state.html", "structtz_1_1gl_1_1vk2_1_1_rasteriser_state" ],
          [ "RenderPass", "classtz_1_1gl_1_1vk2_1_1_render_pass.html", "classtz_1_1gl_1_1vk2_1_1_render_pass" ],
          [ "RenderPassBuilder", "classtz_1_1gl_1_1vk2_1_1_render_pass_builder.html", "classtz_1_1gl_1_1vk2_1_1_render_pass_builder" ],
          [ "RenderPassInfo", "structtz_1_1gl_1_1vk2_1_1_render_pass_info.html", "structtz_1_1gl_1_1vk2_1_1_render_pass_info" ],
          [ "Sampler", "classtz_1_1gl_1_1vk2_1_1_sampler.html", "classtz_1_1gl_1_1vk2_1_1_sampler" ],
          [ "SamplerInfo", "structtz_1_1gl_1_1vk2_1_1_sampler_info.html", "structtz_1_1gl_1_1vk2_1_1_sampler_info" ],
          [ "Shader", "classtz_1_1gl_1_1vk2_1_1_shader.html", null ],
          [ "ShaderInfo", "structtz_1_1gl_1_1vk2_1_1_shader_info.html", "structtz_1_1gl_1_1vk2_1_1_shader_info" ],
          [ "ShaderModule", "classtz_1_1gl_1_1vk2_1_1_shader_module.html", "classtz_1_1gl_1_1vk2_1_1_shader_module" ],
          [ "ShaderModuleInfo", "structtz_1_1gl_1_1vk2_1_1_shader_module_info.html", "structtz_1_1gl_1_1vk2_1_1_shader_module_info" ],
          [ "ShaderPipelineData", "structtz_1_1gl_1_1vk2_1_1_shader_pipeline_data.html", null ],
          [ "SubpassBuilder", "classtz_1_1gl_1_1vk2_1_1_subpass_builder.html", "classtz_1_1gl_1_1vk2_1_1_subpass_builder" ],
          [ "Swapchain", "classtz_1_1gl_1_1vk2_1_1_swapchain.html", "classtz_1_1gl_1_1vk2_1_1_swapchain" ],
          [ "SwapchainImageInfo", "structtz_1_1gl_1_1vk2_1_1_swapchain_image_info.html", "structtz_1_1gl_1_1vk2_1_1_swapchain_image_info" ],
          [ "SwapchainInfo", "structtz_1_1gl_1_1vk2_1_1_swapchain_info.html", "structtz_1_1gl_1_1vk2_1_1_swapchain_info" ],
          [ "TimelineSemaphore", "classtz_1_1gl_1_1vk2_1_1_timeline_semaphore.html", "classtz_1_1gl_1_1vk2_1_1_timeline_semaphore" ],
          [ "VertexInputState", "structtz_1_1gl_1_1vk2_1_1_vertex_input_state.html", "structtz_1_1gl_1_1vk2_1_1_vertex_input_state" ],
          [ "ViewportState", "structtz_1_1gl_1_1vk2_1_1_viewport_state.html", null ],
          [ "VulkanCommand", "structtz_1_1gl_1_1vk2_1_1_vulkan_command.html", "structtz_1_1gl_1_1vk2_1_1_vulkan_command" ],
          [ "VulkanDebugMessenger", "classtz_1_1gl_1_1vk2_1_1_vulkan_debug_messenger.html", null ],
          [ "VulkanInstance", "classtz_1_1gl_1_1vk2_1_1_vulkan_instance.html", null ],
          [ "VulkanInstanceInfo", "structtz_1_1gl_1_1vk2_1_1_vulkan_instance_info.html", "structtz_1_1gl_1_1vk2_1_1_vulkan_instance_info" ],
          [ "WindowSurface", "classtz_1_1gl_1_1vk2_1_1_window_surface.html", "classtz_1_1gl_1_1vk2_1_1_window_surface" ]
        ] ],
        [ "AssetStorageCommon", "classtz_1_1gl_1_1_asset_storage_common.html", null ],
        [ "BufferComponentOGL", "classtz_1_1gl_1_1_buffer_component_o_g_l.html", null ],
        [ "BufferComponentVulkan", "classtz_1_1gl_1_1_buffer_component_vulkan.html", null ],
        [ "BufferResource", "classtz_1_1gl_1_1_buffer_resource.html", null ],
        [ "CommandProcessor", "classtz_1_1gl_1_1_command_processor.html", "classtz_1_1gl_1_1_command_processor" ],
        [ "DeviceOGL", "classtz_1_1gl_1_1_device_o_g_l.html", null ],
        [ "DeviceVulkan", "classtz_1_1gl_1_1_device_vulkan.html", null ],
        [ "DeviceWindowVulkan", "classtz_1_1gl_1_1_device_window_vulkan.html", null ],
        [ "GraphicsPipelineManager", "classtz_1_1gl_1_1_graphics_pipeline_manager.html", "classtz_1_1gl_1_1_graphics_pipeline_manager" ],
        [ "IComponent", "classtz_1_1gl_1_1_i_component.html", null ],
        [ "ImageComponentOGL", "classtz_1_1gl_1_1_image_component_o_g_l.html", null ],
        [ "ImageComponentVulkan", "classtz_1_1gl_1_1_image_component_vulkan.html", null ],
        [ "ImageOutput", "classtz_1_1gl_1_1_image_output.html", null ],
        [ "ImageOutputInfo", "structtz_1_1gl_1_1_image_output_info.html", null ],
        [ "ImageResource", "classtz_1_1gl_1_1_image_resource.html", null ],
        [ "IOutput", "classtz_1_1gl_1_1_i_output.html", null ],
        [ "IResource", "classtz_1_1gl_1_1_i_resource.html", "classtz_1_1gl_1_1_i_resource" ],
        [ "OutputImageState", "structtz_1_1gl_1_1_output_image_state.html", null ],
        [ "OutputImageViewState", "structtz_1_1gl_1_1_output_image_view_state.html", null ],
        [ "OutputManager", "classtz_1_1gl_1_1_output_manager.html", "classtz_1_1gl_1_1_output_manager" ],
        [ "RendererBufferComponentEditRequest", "structtz_1_1gl_1_1_renderer_buffer_component_edit_request.html", "structtz_1_1gl_1_1_renderer_buffer_component_edit_request" ],
        [ "RendererComputeEditRequest", "structtz_1_1gl_1_1_renderer_compute_edit_request.html", "structtz_1_1gl_1_1_renderer_compute_edit_request" ],
        [ "RendererDeviceInfoVulkan", "structtz_1_1gl_1_1_renderer_device_info_vulkan.html", "structtz_1_1gl_1_1_renderer_device_info_vulkan" ],
        [ "RendererEditRequest", "structtz_1_1gl_1_1_renderer_edit_request.html", "structtz_1_1gl_1_1_renderer_edit_request" ],
        [ "RendererImageComponentEditRequest", "structtz_1_1gl_1_1_renderer_image_component_edit_request.html", "structtz_1_1gl_1_1_renderer_image_component_edit_request" ],
        [ "RendererInfoCommon", "classtz_1_1gl_1_1_renderer_info_common.html", "classtz_1_1gl_1_1_renderer_info_common" ],
        [ "RendererOGL", "classtz_1_1gl_1_1_renderer_o_g_l.html", "classtz_1_1gl_1_1_renderer_o_g_l" ],
        [ "RendererResizeInfoVulkan", "structtz_1_1gl_1_1_renderer_resize_info_vulkan.html", null ],
        [ "RendererStateEditRequest", "structtz_1_1gl_1_1_renderer_state_edit_request.html", null ],
        [ "RendererVulkan", "classtz_1_1gl_1_1_renderer_vulkan.html", "classtz_1_1gl_1_1_renderer_vulkan" ],
        [ "Resource", "classtz_1_1gl_1_1_resource.html", "classtz_1_1gl_1_1_resource" ],
        [ "ResourceStorage", "classtz_1_1gl_1_1_resource_storage.html", "classtz_1_1gl_1_1_resource_storage" ],
        [ "ShaderInfo", "classtz_1_1gl_1_1_shader_info.html", null ],
        [ "ShaderManager", "classtz_1_1gl_1_1_shader_manager.html", "classtz_1_1gl_1_1_shader_manager" ],
        [ "ShaderMeta", "structtz_1_1gl_1_1_shader_meta.html", null ],
        [ "WindowOutput", "classtz_1_1gl_1_1_window_output.html", null ]
      ] ],
      [ "AllocatorAdapter", "classtz_1_1_allocator_adapter.html", null ],
      [ "BasicList", "classtz_1_1_basic_list.html", "classtz_1_1_basic_list" ],
      [ "Blk", "structtz_1_1_blk.html", "structtz_1_1_blk" ],
      [ "Callback", "classtz_1_1_callback.html", "classtz_1_1_callback" ],
      [ "Delay", "classtz_1_1_delay.html", "classtz_1_1_delay" ],
      [ "Duration", "classtz_1_1_duration.html", "classtz_1_1_duration" ],
      [ "EngineInfo", "structtz_1_1_engine_info.html", "structtz_1_1_engine_info" ],
      [ "EnumField", "classtz_1_1_enum_field.html", "classtz_1_1_enum_field" ],
      [ "FallbackAllocator", "classtz_1_1_fallback_allocator.html", null ],
      [ "GameInfo", "structtz_1_1_game_info.html", "structtz_1_1_game_info" ],
      [ "GridView", "classtz_1_1_grid_view.html", "classtz_1_1_grid_view" ],
      [ "Handle", "classtz_1_1_handle.html", "classtz_1_1_handle" ],
      [ "InitialiseInfo", "structtz_1_1_initialise_info.html", "structtz_1_1_initialise_info" ],
      [ "InterfaceIterator", "classtz_1_1_interface_iterator.html", null ],
      [ "IUniqueCloneable", "classtz_1_1_i_unique_cloneable.html", null ],
      [ "KeyboardState", "classtz_1_1_keyboard_state.html", "classtz_1_1_keyboard_state" ],
      [ "KeyInfo", "structtz_1_1_key_info.html", "structtz_1_1_key_info" ],
      [ "KeyPressInfo", "structtz_1_1_key_press_info.html", "structtz_1_1_key_press_info" ],
      [ "LinearAllocator", "classtz_1_1_linear_allocator.html", null ],
      [ "Mallocator", "classtz_1_1_mallocator.html", null ],
      [ "Matrix", "classtz_1_1_matrix.html", "classtz_1_1_matrix" ],
      [ "MaybeOwnedPtr", "classtz_1_1_maybe_owned_ptr.html", null ],
      [ "MonitorInfo", "structtz_1_1_monitor_info.html", "structtz_1_1_monitor_info" ],
      [ "MouseButtonInfo", "structtz_1_1_mouse_button_info.html", null ],
      [ "MouseButtonPressInfo", "structtz_1_1_mouse_button_press_info.html", null ],
      [ "MouseButtonState", "classtz_1_1_mouse_button_state.html", "classtz_1_1_mouse_button_state" ],
      [ "MousePositionInfo", "structtz_1_1_mouse_position_info.html", null ],
      [ "MousePositionState", "classtz_1_1_mouse_position_state.html", "classtz_1_1_mouse_position_state" ],
      [ "NullAllocator", "classtz_1_1_null_allocator.html", null ],
      [ "nullhand_t", "structtz_1_1nullhand__t.html", null ],
      [ "PolymorphicList", "classtz_1_1_polymorphic_list.html", "classtz_1_1_polymorphic_list" ],
      [ "StackAllocator", "classtz_1_1_stack_allocator.html", null ],
      [ "Vector", "classtz_1_1_vector.html", "classtz_1_1_vector" ],
      [ "Version", "structtz_1_1_version.html", null ],
      [ "Window", "classtz_1_1_window.html", "classtz_1_1_window" ],
      [ "WindowExtraFlags", "structtz_1_1_window_extra_flags.html", "structtz_1_1_window_extra_flags" ],
      [ "WindowFunctionality", "classtz_1_1_window_functionality.html", "classtz_1_1_window_functionality" ],
      [ "WindowHint", "structtz_1_1_window_hint.html", null ],
      [ "WindowInitArgs", "structtz_1_1_window_init_args.html", "structtz_1_1_window_init_args" ]
    ] ],
    [ "Renderer", "class_renderer.html", null ]
];