var hierarchy =
[
    [ "tz::gl::vk2::CommandPool::Allocation", "structtz_1_1gl_1_1vk2_1_1_command_pool_1_1_allocation.html", null ],
    [ "tz::gl::vk2::DescriptorPool::Allocation", "structtz_1_1gl_1_1vk2_1_1_descriptor_pool_1_1_allocation.html", null ],
    [ "tz::gl::vk2::CommandPool::AllocationResult", "structtz_1_1gl_1_1vk2_1_1_command_pool_1_1_allocation_result.html", null ],
    [ "tz::gl::vk2::DescriptorPool::AllocationResult", "structtz_1_1gl_1_1vk2_1_1_descriptor_pool_1_1_allocation_result.html", null ],
    [ "tz::gl::AssetStorageCommon< Asset >", "classtz_1_1gl_1_1_asset_storage_common.html", null ],
    [ "tz::gl::AssetStorageCommon< IResource >", "classtz_1_1gl_1_1_asset_storage_common.html", [
      [ "tz::gl::ResourceStorage", "classtz_1_1gl_1_1_resource_storage.html", null ],
      [ "tz::gl::ResourceStorage", "classtz_1_1gl_1_1_resource_storage.html", null ]
    ] ],
    [ "tz::gl::vk2::Attachment", "structtz_1_1gl_1_1vk2_1_1_attachment.html", null ],
    [ "tz::gl::vk2::RenderPassInfo::AttachmentReference", "structtz_1_1gl_1_1vk2_1_1_render_pass_info_1_1_attachment_reference.html", null ],
    [ "tz::gl::vk2::VertexInputState::Attribute", "structtz_1_1gl_1_1vk2_1_1_vertex_input_state_1_1_attribute.html", null ],
    [ "tz::BasicList< T, Allocator >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< AttachmentState >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< const tz::gl::vk2::BinarySemaphore * >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< const tz::gl::vk2::CommandBuffer * >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< const tz::gl::vk2::DescriptorLayout * >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< const tz::gl::vk2::DescriptorSet * >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< FramebufferTexture >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< SmartPointer, std::allocator< std::unique_ptr< T > > >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< std::uint32_t >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< tz::BasicList >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< tz::gl::IComponent * >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< tz::gl::ogl2::ShaderModuleInfo >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< tz::gl::vk2::Attachment >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< tz::gl::vk2::CommandBuffer >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< tz::gl::vk2::DescriptorLayoutInfo::BindingInfo >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< tz::gl::vk2::DescriptorSet >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< tz::gl::vk2::hardware::Queue::SubmitInfo::WaitInfo >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< tz::gl::vk2::Image * >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< tz::gl::vk2::ImageView * >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< tz::gl::vk2::ImageView >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< tz::gl::vk2::RenderPassInfo::AttachmentReference >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< tz::gl::vk2::RenderPassInfo::InputAttachmentReference >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< tz::gl::vk2::RenderPassInfo::Subpass >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< tz::gl::vk2::ShaderModuleInfo >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< tz::gl::vk2::VertexInputState::Attribute >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< tz::gl::vk2::VertexInputState::Binding >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< VkPipelineShaderStageCreateInfo >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< VkRect2D >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< VkViewport >", "classtz_1_1_basic_list.html", null ],
    [ "tz::BasicList< Write >", "classtz_1_1_basic_list.html", null ],
    [ "tz::gl::vk2::VulkanCommand::BeginRenderPass", "structtz_1_1gl_1_1vk2_1_1_vulkan_command_1_1_begin_render_pass.html", null ],
    [ "tz::gl::vk2::VulkanCommand::BindBuffer", "structtz_1_1gl_1_1vk2_1_1_vulkan_command_1_1_bind_buffer.html", null ],
    [ "tz::gl::vk2::VulkanCommand::BindDescriptorSets", "structtz_1_1gl_1_1vk2_1_1_vulkan_command_1_1_bind_descriptor_sets.html", null ],
    [ "tz::gl::vk2::VulkanCommand::BindIndexBuffer", "structtz_1_1gl_1_1vk2_1_1_vulkan_command_1_1_bind_index_buffer.html", null ],
    [ "tz::gl::vk2::VertexInputState::Binding", "structtz_1_1gl_1_1vk2_1_1_vertex_input_state_1_1_binding.html", null ],
    [ "tz::gl::vk2::DescriptorLayoutInfo::BindingInfo", "structtz_1_1gl_1_1vk2_1_1_descriptor_layout_info_1_1_binding_info.html", null ],
    [ "tz::gl::vk2::VulkanCommand::BindPipeline", "structtz_1_1gl_1_1vk2_1_1_vulkan_command_1_1_bind_pipeline.html", null ],
    [ "tz::Blk", "structtz_1_1_blk.html", null ],
    [ "tz::gl::ogl2::Buffer", "classtz_1_1gl_1_1ogl2_1_1_buffer.html", null ],
    [ "tz::gl::vk2::VulkanCommand::BufferCopyBuffer", "structtz_1_1gl_1_1vk2_1_1_vulkan_command_1_1_buffer_copy_buffer.html", null ],
    [ "tz::gl::vk2::VulkanCommand::BufferCopyImage", "structtz_1_1gl_1_1vk2_1_1_vulkan_command_1_1_buffer_copy_image.html", null ],
    [ "tz::gl::ogl2::BufferInfo", "structtz_1_1gl_1_1ogl2_1_1_buffer_info.html", null ],
    [ "tz::gl::vk2::BufferInfo", "structtz_1_1gl_1_1vk2_1_1_buffer_info.html", null ],
    [ "tz::gl::vk2::DescriptorSet::Write::BufferWriteInfo", "structtz_1_1gl_1_1vk2_1_1_descriptor_set_1_1_write_1_1_buffer_write_info.html", null ],
    [ "tz::Callback< Args >", "classtz_1_1_callback.html", null ],
    [ "tz::Callback< RendererResizeInfoVulkan >", "classtz_1_1_callback.html", null ],
    [ "tz::Callback< tz::Vec2ui >", "classtz_1_1_callback.html", null ],
    [ "tz::detail::CallbackType", "structtz_1_1detail_1_1_callback_type.html", null ],
    [ "tz::gl::vk2::ColourBlendState", "structtz_1_1gl_1_1vk2_1_1_colour_blend_state.html", null ],
    [ "tz::gl::vk2::CommandBuffer", "classtz_1_1gl_1_1vk2_1_1_command_buffer.html", null ],
    [ "tz::gl::vk2::CommandBufferRecording", "classtz_1_1gl_1_1vk2_1_1_command_buffer_recording.html", null ],
    [ "tz::gl::vk2::CommandPool", "classtz_1_1gl_1_1vk2_1_1_command_pool.html", null ],
    [ "tz::gl::vk2::CommandPoolInfo", "structtz_1_1gl_1_1vk2_1_1_command_pool_info.html", null ],
    [ "tz::gl::CommandProcessor", "classtz_1_1gl_1_1_command_processor.html", null ],
    [ "tz::gl::ogl2::ShaderModule::CompileResult", "structtz_1_1gl_1_1ogl2_1_1_shader_module_1_1_compile_result.html", null ],
    [ "tz::gl::vk2::ComputePipeline", "classtz_1_1gl_1_1vk2_1_1_compute_pipeline.html", null ],
    [ "tz::gl::vk2::ComputePipelineInfo", "structtz_1_1gl_1_1vk2_1_1_compute_pipeline_info.html", null ],
    [ "tz::gl::vk2::VulkanCommand::DebugBeginLabel", "structtz_1_1gl_1_1vk2_1_1_vulkan_command_1_1_debug_begin_label.html", null ],
    [ "tz::gl::vk2::VulkanCommand::DebugEndLabel", "structtz_1_1gl_1_1vk2_1_1_vulkan_command_1_1_debug_end_label.html", null ],
    [ "tz::gl::vk2::DebugNameable< T >", "classtz_1_1gl_1_1vk2_1_1_debug_nameable.html", null ],
    [ "tz::gl::vk2::DebugNameable< VK_OBJECT_TYPE_BUFFER >", "classtz_1_1gl_1_1vk2_1_1_debug_nameable.html", [
      [ "tz::gl::vk2::Buffer", "classtz_1_1gl_1_1vk2_1_1_buffer.html", null ]
    ] ],
    [ "tz::gl::vk2::DebugNameable< VK_OBJECT_TYPE_FENCE >", "classtz_1_1gl_1_1vk2_1_1_debug_nameable.html", [
      [ "tz::gl::vk2::Fence", "classtz_1_1gl_1_1vk2_1_1_fence.html", null ]
    ] ],
    [ "tz::gl::vk2::DebugNameable< VK_OBJECT_TYPE_IMAGE >", "classtz_1_1gl_1_1vk2_1_1_debug_nameable.html", [
      [ "tz::gl::vk2::Image", "classtz_1_1gl_1_1vk2_1_1_image.html", null ]
    ] ],
    [ "tz::gl::vk2::DebugNameable< VK_OBJECT_TYPE_IMAGE_VIEW >", "classtz_1_1gl_1_1vk2_1_1_debug_nameable.html", [
      [ "tz::gl::vk2::ImageView", "classtz_1_1gl_1_1vk2_1_1_image_view.html", null ]
    ] ],
    [ "tz::gl::vk2::DebugNameable< VK_OBJECT_TYPE_SEMAPHORE >", "classtz_1_1gl_1_1vk2_1_1_debug_nameable.html", [
      [ "tz::gl::vk2::BinarySemaphore", "classtz_1_1gl_1_1vk2_1_1_binary_semaphore.html", [
        [ "tz::gl::vk2::TimelineSemaphore", "classtz_1_1gl_1_1vk2_1_1_timeline_semaphore.html", null ]
      ] ]
    ] ],
    [ "tz::Delay", "classtz_1_1_delay.html", null ],
    [ "tz::gl::vk2::DepthStencilState", "structtz_1_1gl_1_1vk2_1_1_depth_stencil_state.html", null ],
    [ "tz::gl::vk2::DescriptorLayout", "classtz_1_1gl_1_1vk2_1_1_descriptor_layout.html", null ],
    [ "tz::gl::vk2::DescriptorLayoutBuilder", "classtz_1_1gl_1_1vk2_1_1_descriptor_layout_builder.html", null ],
    [ "tz::gl::vk2::DescriptorLayoutInfo", "structtz_1_1gl_1_1vk2_1_1_descriptor_layout_info.html", null ],
    [ "tz::gl::vk2::DescriptorPool", "classtz_1_1gl_1_1vk2_1_1_descriptor_pool.html", null ],
    [ "tz::gl::vk2::DescriptorPoolInfo", "structtz_1_1gl_1_1vk2_1_1_descriptor_pool_info.html", null ],
    [ "tz::gl::vk2::DescriptorSet", "classtz_1_1gl_1_1vk2_1_1_descriptor_set.html", null ],
    [ "tz::gl::vk2::detail::DeviceFeatureInfo", "structtz_1_1gl_1_1vk2_1_1detail_1_1_device_feature_info.html", null ],
    [ "tz::gl::DeviceOGL", "classtz_1_1gl_1_1_device_o_g_l.html", null ],
    [ "tz::gl::DeviceRenderSchedulerVulkan", "classtz_1_1gl_1_1_device_render_scheduler_vulkan.html", null ],
    [ "tz::gl::DeviceVulkan", "classtz_1_1gl_1_1_device_vulkan.html", null ],
    [ "tz::gl::DeviceWindowVulkan", "classtz_1_1gl_1_1_device_window_vulkan.html", null ],
    [ "tz::gl::vk2::VulkanCommand::Dispatch", "structtz_1_1gl_1_1vk2_1_1_vulkan_command_1_1_dispatch.html", null ],
    [ "tz::gl::vk2::VulkanCommand::Draw", "structtz_1_1gl_1_1vk2_1_1_vulkan_command_1_1_draw.html", null ],
    [ "tz::gl::vk2::VulkanCommand::DrawIndexed", "structtz_1_1gl_1_1vk2_1_1_vulkan_command_1_1_draw_indexed.html", null ],
    [ "tz::Duration", "classtz_1_1_duration.html", null ],
    [ "tz::gl::vk2::DynamicState", "structtz_1_1gl_1_1vk2_1_1_dynamic_state.html", null ],
    [ "tz::gl::vk2::DescriptorSet::EditRequest", "classtz_1_1gl_1_1vk2_1_1_descriptor_set_1_1_edit_request.html", null ],
    [ "tz::gl::vk2::VulkanCommand::EndRenderPass", "structtz_1_1gl_1_1vk2_1_1_vulkan_command_1_1_end_render_pass.html", null ],
    [ "tz::EngineInfo", "structtz_1_1_engine_info.html", null ],
    [ "tz::EnumField< E >", "classtz_1_1_enum_field.html", null ],
    [ "tz::EnumField< AccessFlag >", "classtz_1_1_enum_field.html", null ],
    [ "tz::EnumField< ApplicationFlag >", "classtz_1_1_enum_field.html", null ],
    [ "tz::EnumField< BufferUsage >", "classtz_1_1_enum_field.html", null ],
    [ "tz::EnumField< CommandPoolFlag >", "classtz_1_1_enum_field.html", null ],
    [ "tz::EnumField< DescriptorFlag >", "classtz_1_1_enum_field.html", null ],
    [ "tz::EnumField< DeviceExtension >", "classtz_1_1_enum_field.html", null ],
    [ "tz::EnumField< DeviceFeature >", "classtz_1_1_enum_field.html", null ],
    [ "tz::EnumField< ImageAspectFlag >", "classtz_1_1_enum_field.html", null ],
    [ "tz::EnumField< ImageUsage >", "classtz_1_1_enum_field.html", null ],
    [ "tz::EnumField< InstanceExtension >", "classtz_1_1_enum_field.html", null ],
    [ "tz::EnumField< QueueFamilyType >", "classtz_1_1_enum_field.html", null ],
    [ "tz::EnumField< RendererOption >", "classtz_1_1_enum_field.html", null ],
    [ "tz::EnumField< ResourceFlag >", "classtz_1_1_enum_field.html", null ],
    [ "tz::gl::vk2::FenceInfo", "structtz_1_1gl_1_1vk2_1_1_fence_info.html", null ],
    [ "tz::gl::ogl2::FormatData", "structtz_1_1gl_1_1ogl2_1_1_format_data.html", null ],
    [ "tz::gl::ogl2::Framebuffer", "classtz_1_1gl_1_1ogl2_1_1_framebuffer.html", null ],
    [ "tz::gl::vk2::Framebuffer", "classtz_1_1gl_1_1vk2_1_1_framebuffer.html", null ],
    [ "tz::gl::ogl2::FramebufferInfo", "structtz_1_1gl_1_1ogl2_1_1_framebuffer_info.html", null ],
    [ "tz::gl::vk2::FramebufferInfo", "structtz_1_1gl_1_1vk2_1_1_framebuffer_info.html", null ],
    [ "tz::GameInfo", "structtz_1_1_game_info.html", null ],
    [ "tz::gl::vk2::GraphicsPipeline", "classtz_1_1gl_1_1vk2_1_1_graphics_pipeline.html", null ],
    [ "tz::gl::vk2::GraphicsPipelineInfo", "structtz_1_1gl_1_1vk2_1_1_graphics_pipeline_info.html", null ],
    [ "tz::gl::GraphicsPipelineManager", "classtz_1_1gl_1_1_graphics_pipeline_manager.html", null ],
    [ "tz::GridView< T, N >", "classtz_1_1_grid_view.html", null ],
    [ "tz::Handle< T >", "classtz_1_1_handle.html", null ],
    [ "tz::Handle< detail::CallbackType >", "classtz_1_1_handle.html", null ],
    [ "tz::Handle< IResource >", "classtz_1_1_handle.html", null ],
    [ "std::hash< tz::Handle< T > >", "structstd_1_1hash_3_01tz_1_1_handle_3_01_t_01_4_01_4.html", null ],
    [ "tz::gl::IComponent", "classtz_1_1gl_1_1_i_component.html", [
      [ "tz::gl::BufferComponentOGL", "classtz_1_1gl_1_1_buffer_component_o_g_l.html", null ],
      [ "tz::gl::BufferComponentVulkan", "classtz_1_1gl_1_1_buffer_component_vulkan.html", null ],
      [ "tz::gl::ImageComponentOGL", "classtz_1_1gl_1_1_image_component_o_g_l.html", null ],
      [ "tz::gl::ImageComponentVulkan", "classtz_1_1gl_1_1_image_component_vulkan.html", null ]
    ] ],
    [ "tz::gl::ogl2::Image", "classtz_1_1gl_1_1ogl2_1_1_image.html", null ],
    [ "tz::gl::vk2::Swapchain::ImageAcquisition", "structtz_1_1gl_1_1vk2_1_1_swapchain_1_1_image_acquisition.html", null ],
    [ "tz::gl::vk2::Swapchain::ImageAcquisitionResult", "structtz_1_1gl_1_1vk2_1_1_swapchain_1_1_image_acquisition_result.html", null ],
    [ "tz::gl::vk2::VulkanCommand::ImageCopyImage", "structtz_1_1gl_1_1vk2_1_1_vulkan_command_1_1_image_copy_image.html", null ],
    [ "tz::gl::ogl2::ImageInfo", "structtz_1_1gl_1_1ogl2_1_1_image_info.html", null ],
    [ "tz::gl::vk2::ImageInfo", "structtz_1_1gl_1_1vk2_1_1_image_info.html", null ],
    [ "tz::gl::ImageOutputInfo", "structtz_1_1gl_1_1_image_output_info.html", null ],
    [ "tz::gl::vk2::ImageViewInfo", "structtz_1_1gl_1_1vk2_1_1_image_view_info.html", null ],
    [ "tz::gl::vk2::DescriptorSet::Write::ImageWriteInfo", "structtz_1_1gl_1_1vk2_1_1_descriptor_set_1_1_write_1_1_image_write_info.html", null ],
    [ "tz::InitialiseInfo", "structtz_1_1_initialise_info.html", null ],
    [ "tz::gl::vk2::RenderPassInfo::InputAttachmentReference", "structtz_1_1gl_1_1vk2_1_1_render_pass_info_1_1_input_attachment_reference.html", null ],
    [ "tz::InterfaceIterator< T >", "classtz_1_1_interface_iterator.html", null ],
    [ "tz::gl::vk2::InternalDeviceInfo", "structtz_1_1gl_1_1vk2_1_1_internal_device_info.html", null ],
    [ "tz::gl::IResource", "classtz_1_1gl_1_1_i_resource.html", [
      [ "tz::gl::Resource", "classtz_1_1gl_1_1_resource.html", [
        [ "tz::gl::BufferResource", "classtz_1_1gl_1_1_buffer_resource.html", null ],
        [ "tz::gl::ImageResource", "classtz_1_1gl_1_1_image_resource.html", null ]
      ] ]
    ] ],
    [ "tz::IUniqueCloneable< T >", "classtz_1_1_i_unique_cloneable.html", null ],
    [ "tz::IUniqueCloneable< IOutput >", "classtz_1_1_i_unique_cloneable.html", [
      [ "tz::gl::IOutput", "classtz_1_1gl_1_1_i_output.html", [
        [ "tz::gl::ImageOutput", "classtz_1_1gl_1_1_image_output.html", null ],
        [ "tz::gl::WindowOutput", "classtz_1_1gl_1_1_window_output.html", null ]
      ] ]
    ] ],
    [ "tz::KeyboardState", "classtz_1_1_keyboard_state.html", null ],
    [ "tz::KeyInfo", "structtz_1_1_key_info.html", null ],
    [ "tz::KeyPressInfo", "structtz_1_1_key_press_info.html", null ],
    [ "tz::LinearAllocator", "classtz_1_1_linear_allocator.html", [
      [ "tz::StackAllocator< S >", "classtz_1_1_stack_allocator.html", null ]
    ] ],
    [ "tz::gl::ogl2::Shader::LinkResult", "structtz_1_1gl_1_1ogl2_1_1_shader_1_1_link_result.html", null ],
    [ "tz::gl::vk2::LogicalDevice", "classtz_1_1gl_1_1vk2_1_1_logical_device.html", null ],
    [ "tz::gl::vk2::LogicalDeviceInfo", "structtz_1_1gl_1_1vk2_1_1_logical_device_info.html", null ],
    [ "tz::Mallocator", "classtz_1_1_mallocator.html", null ],
    [ "tz::Matrix< T, R, C >", "classtz_1_1_matrix.html", null ],
    [ "tz::MaybeOwnedPtr< T >", "classtz_1_1_maybe_owned_ptr.html", null ],
    [ "tz::MonitorInfo", "structtz_1_1_monitor_info.html", null ],
    [ "tz::MouseButtonInfo", "structtz_1_1_mouse_button_info.html", null ],
    [ "tz::MouseButtonPressInfo", "structtz_1_1_mouse_button_press_info.html", null ],
    [ "tz::MouseButtonState", "classtz_1_1_mouse_button_state.html", null ],
    [ "tz::MousePositionInfo", "structtz_1_1_mouse_position_info.html", null ],
    [ "tz::MousePositionState", "classtz_1_1_mouse_position_state.html", null ],
    [ "tz::gl::vk2::MultisampleState", "structtz_1_1gl_1_1vk2_1_1_multisample_state.html", null ],
    [ "tz::space::MVP", "structtz_1_1space_1_1_m_v_p.html", null ],
    [ "tz::NullAllocator", "classtz_1_1_null_allocator.html", null ],
    [ "tz::nullhand_t", "structtz_1_1nullhand__t.html", null ],
    [ "tz::gl::OutputImageState", "structtz_1_1gl_1_1_output_image_state.html", null ],
    [ "tz::gl::OutputImageViewState", "structtz_1_1gl_1_1_output_image_view_state.html", null ],
    [ "tz::gl::OutputManager", "classtz_1_1gl_1_1_output_manager.html", null ],
    [ "tz::gl::vk2::PhysicalDevice", "classtz_1_1gl_1_1vk2_1_1_physical_device.html", null ],
    [ "tz::gl::vk2::PhysicalDeviceInfo", "structtz_1_1gl_1_1vk2_1_1_physical_device_info.html", null ],
    [ "tz::gl::vk2::PhysicalDeviceSurfaceCapabilityInfo", "structtz_1_1gl_1_1vk2_1_1_physical_device_surface_capability_info.html", null ],
    [ "tz::gl::vk2::Pipeline", "classtz_1_1gl_1_1vk2_1_1_pipeline.html", null ],
    [ "tz::gl::vk2::PipelineLayout", "classtz_1_1gl_1_1vk2_1_1_pipeline_layout.html", null ],
    [ "tz::gl::vk2::PipelineLayoutInfo", "structtz_1_1gl_1_1vk2_1_1_pipeline_layout_info.html", null ],
    [ "tz::gl::vk2::PipelineState", "structtz_1_1gl_1_1vk2_1_1_pipeline_state.html", null ],
    [ "tz::PolymorphicList< T, Allocator >", "classtz_1_1_polymorphic_list.html", null ],
    [ "tz::gl::vk2::DescriptorPoolInfo::PoolLimits", "structtz_1_1gl_1_1vk2_1_1_descriptor_pool_info_1_1_pool_limits.html", null ],
    [ "tz::gl::vk2::hardware::Queue::PresentInfo", "structtz_1_1gl_1_1vk2_1_1hardware_1_1_queue_1_1_present_info.html", null ],
    [ "tz::gl::vk2::hardware::Queue", "classtz_1_1gl_1_1vk2_1_1hardware_1_1_queue.html", null ],
    [ "tz::gl::vk2::QueueFamilyInfo", "structtz_1_1gl_1_1vk2_1_1_queue_family_info.html", null ],
    [ "tz::gl::vk2::hardware::QueueInfo", "structtz_1_1gl_1_1vk2_1_1hardware_1_1_queue_info.html", null ],
    [ "tz::gl::vk2::QueueRequest", "structtz_1_1gl_1_1vk2_1_1_queue_request.html", null ],
    [ "tz::gl::vk2::QueueStorage", "classtz_1_1gl_1_1vk2_1_1_queue_storage.html", null ],
    [ "tz::gl::vk2::RasteriserState", "structtz_1_1gl_1_1vk2_1_1_rasteriser_state.html", null ],
    [ "tz::gl::ogl2::Renderbuffer", "classtz_1_1gl_1_1ogl2_1_1_renderbuffer.html", null ],
    [ "tz::gl::ogl2::RenderbufferInfo", "structtz_1_1gl_1_1ogl2_1_1_renderbuffer_info.html", null ],
    [ "Renderer", "class_renderer.html", null ],
    [ "tz::gl::RendererBufferComponentResizeRequest", "structtz_1_1gl_1_1_renderer_buffer_component_resize_request.html", null ],
    [ "tz::gl::RendererComponentWriteRequest", "structtz_1_1gl_1_1_renderer_component_write_request.html", null ],
    [ "tz::gl::RendererComputeEditRequest", "structtz_1_1gl_1_1_renderer_compute_edit_request.html", null ],
    [ "tz::gl::RendererDeviceInfoVulkan", "structtz_1_1gl_1_1_renderer_device_info_vulkan.html", null ],
    [ "tz::gl::RendererEditBuilder", "classtz_1_1gl_1_1_renderer_edit_builder.html", null ],
    [ "tz::gl::RendererEditRequest", "structtz_1_1gl_1_1_renderer_edit_request.html", null ],
    [ "tz::gl::RendererImageComponentResizeRequest", "structtz_1_1gl_1_1_renderer_image_component_resize_request.html", null ],
    [ "tz::gl::RendererInfoCommon", "classtz_1_1gl_1_1_renderer_info_common.html", null ],
    [ "tz::gl::RendererOGL", "classtz_1_1gl_1_1_renderer_o_g_l.html", null ],
    [ "tz::gl::RendererResizeInfoVulkan", "structtz_1_1gl_1_1_renderer_resize_info_vulkan.html", null ],
    [ "tz::gl::RendererStateEditRequest", "structtz_1_1gl_1_1_renderer_state_edit_request.html", null ],
    [ "tz::gl::RendererVulkan", "classtz_1_1gl_1_1_renderer_vulkan.html", null ],
    [ "tz::gl::vk2::RenderPass", "classtz_1_1gl_1_1vk2_1_1_render_pass.html", null ],
    [ "tz::gl::vk2::RenderPassBuilder", "classtz_1_1gl_1_1vk2_1_1_render_pass_builder.html", null ],
    [ "tz::gl::vk2::RenderPassInfo", "structtz_1_1gl_1_1vk2_1_1_render_pass_info.html", null ],
    [ "tz::gl::vk2::CommandBufferRecording::RenderPassRun", "classtz_1_1gl_1_1vk2_1_1_command_buffer_recording_1_1_render_pass_run.html", null ],
    [ "tz::gl::CommandProcessor::RenderWorkSubmitResult", "structtz_1_1gl_1_1_command_processor_1_1_render_work_submit_result.html", null ],
    [ "tz::gl::ogl2::Sampler", "structtz_1_1gl_1_1ogl2_1_1_sampler.html", null ],
    [ "tz::gl::vk2::Sampler", "classtz_1_1gl_1_1vk2_1_1_sampler.html", null ],
    [ "tz::gl::vk2::SamplerInfo", "structtz_1_1gl_1_1vk2_1_1_sampler_info.html", null ],
    [ "tz::gl::ogl2::Shader", "classtz_1_1gl_1_1ogl2_1_1_shader.html", null ],
    [ "tz::gl::vk2::Shader", "classtz_1_1gl_1_1vk2_1_1_shader.html", null ],
    [ "tz::gl::ogl2::ShaderInfo", "structtz_1_1gl_1_1ogl2_1_1_shader_info.html", null ],
    [ "tz::gl::ShaderInfo", "classtz_1_1gl_1_1_shader_info.html", null ],
    [ "tz::gl::vk2::ShaderInfo", "structtz_1_1gl_1_1vk2_1_1_shader_info.html", null ],
    [ "tz::gl::ShaderManager", "classtz_1_1gl_1_1_shader_manager.html", null ],
    [ "tz::gl::ShaderMeta", "structtz_1_1gl_1_1_shader_meta.html", null ],
    [ "tz::gl::ogl2::ShaderModule", "classtz_1_1gl_1_1ogl2_1_1_shader_module.html", null ],
    [ "tz::gl::vk2::ShaderModule", "classtz_1_1gl_1_1vk2_1_1_shader_module.html", null ],
    [ "tz::gl::ogl2::ShaderModuleInfo", "structtz_1_1gl_1_1ogl2_1_1_shader_module_info.html", null ],
    [ "tz::gl::vk2::ShaderModuleInfo", "structtz_1_1gl_1_1vk2_1_1_shader_module_info.html", null ],
    [ "tz::gl::vk2::ShaderPipelineData", "structtz_1_1gl_1_1vk2_1_1_shader_pipeline_data.html", null ],
    [ "tz::gl::vk2::hardware::Queue::SubmitInfo", "structtz_1_1gl_1_1vk2_1_1hardware_1_1_queue_1_1_submit_info.html", null ],
    [ "tz::gl::vk2::RenderPassInfo::Subpass", "structtz_1_1gl_1_1vk2_1_1_render_pass_info_1_1_subpass.html", null ],
    [ "tz::gl::vk2::SubpassBuilder", "classtz_1_1gl_1_1vk2_1_1_subpass_builder.html", null ],
    [ "tz::gl::vk2::Swapchain", "classtz_1_1gl_1_1vk2_1_1_swapchain.html", null ],
    [ "tz::gl::vk2::PhysicalDeviceSurfaceCapabilityInfo::SwapchainExtent", "structtz_1_1gl_1_1vk2_1_1_physical_device_surface_capability_info_1_1_swapchain_extent.html", null ],
    [ "tz::gl::vk2::SwapchainImageInfo", "structtz_1_1gl_1_1vk2_1_1_swapchain_image_info.html", null ],
    [ "tz::gl::vk2::SwapchainInfo", "structtz_1_1gl_1_1vk2_1_1_swapchain_info.html", null ],
    [ "tz::gl::vk2::VulkanCommand::TransitionImageLayout", "structtz_1_1gl_1_1vk2_1_1_vulkan_command_1_1_transition_image_layout.html", null ],
    [ "tz::gl::vk2::DescriptorPool::UpdateRequest", "classtz_1_1gl_1_1vk2_1_1_descriptor_pool_1_1_update_request.html", null ],
    [ "tz::Vector< T, S >", "classtz_1_1_vector.html", null ],
    [ "tz::Vector< float, 2 >", "classtz_1_1_vector.html", null ],
    [ "tz::Vector< float, 4 >", "classtz_1_1_vector.html", null ],
    [ "tz::Vector< std::uint32_t, 2 >", "classtz_1_1_vector.html", null ],
    [ "tz::Vector< unsigned int, 2 >", "classtz_1_1_vector.html", null ],
    [ "tz::Vector< unsigned int, 3 >", "classtz_1_1_vector.html", null ],
    [ "tz::Version", "structtz_1_1_version.html", null ],
    [ "tz::gl::ogl2::VertexArray", "classtz_1_1gl_1_1ogl2_1_1_vertex_array.html", null ],
    [ "tz::gl::vk2::VertexInputState", "structtz_1_1gl_1_1vk2_1_1_vertex_input_state.html", null ],
    [ "tz::gl::vk2::ViewportState", "structtz_1_1gl_1_1vk2_1_1_viewport_state.html", null ],
    [ "tz::gl::vk2::VulkanCommand", "structtz_1_1gl_1_1vk2_1_1_vulkan_command.html", null ],
    [ "tz::gl::vk2::VulkanDebugMessenger", "classtz_1_1gl_1_1vk2_1_1_vulkan_debug_messenger.html", null ],
    [ "tz::gl::vk2::VulkanInstance", "classtz_1_1gl_1_1vk2_1_1_vulkan_instance.html", null ],
    [ "tz::gl::vk2::VulkanInstanceInfo", "structtz_1_1gl_1_1vk2_1_1_vulkan_instance_info.html", null ],
    [ "tz::gl::vk2::hardware::Queue::SubmitInfo::WaitInfo", "structtz_1_1gl_1_1vk2_1_1hardware_1_1_queue_1_1_submit_info_1_1_wait_info.html", null ],
    [ "tz::WindowExtraFlags", "structtz_1_1_window_extra_flags.html", null ],
    [ "tz::WindowFunctionality", "classtz_1_1_window_functionality.html", [
      [ "tz::Window", "classtz_1_1_window.html", null ]
    ] ],
    [ "tz::WindowInitArgs", "structtz_1_1_window_init_args.html", null ],
    [ "tz::gl::vk2::WindowSurface", "classtz_1_1gl_1_1vk2_1_1_window_surface.html", null ],
    [ "tz::gl::vk2::DescriptorSet::Write", "structtz_1_1gl_1_1vk2_1_1_descriptor_set_1_1_write.html", null ],
    [ "tz::A", null, [
      [ "tz::AllocatorAdapter< T, A >", "classtz_1_1_allocator_adapter.html", null ]
    ] ],
    [ "tz::Primary", null, [
      [ "tz::FallbackAllocator< Primary, Secondary >", "classtz_1_1_fallback_allocator.html", null ]
    ] ],
    [ "tz::Secondary", null, [
      [ "tz::FallbackAllocator< Primary, Secondary >", "classtz_1_1_fallback_allocator.html", null ]
    ] ]
];