#ifndef TOPAZ_TRANSFORM_HPP
#define TOPAZ_TRANSFORM_HPP
#include "data/matrix.hpp"

class Transform
{
public:
    /**
     * Create a transform from all specifications.
     * @param position - 3-dimensional Vector representing the position, in world-space
     * @param rotation - 3-dimensional Vector representing the rotation, in euler-angles (radians)
     * @param scale - 3-dimensional Vector representing the scale in each spatial dimension
     */
    Transform(Vector3F position, Vector3F rotation, Vector3F scale);
    /**
     * Get the model matrix.
     * @return - The model-matrix generated by this Transform
     */
    Matrix4x4 model() const;
    bool operator==(const Transform& rhs) const;
    /// Position, in world-space.
    Vector3F position;
    /// Rotation, in euler-angles.
    Vector3F rotation;
    /// Scale in each dimension.
    Vector3F scale;
};

#endif //TOPAZ_TRANSFORM_HPP
