name: "MSVC Code Build"
on:
  workflow_call:
    inputs:
      render_api:
        required: true
        type: string
      build_config:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: 'Install Vulkan SDK'
        uses: humbletim/install-vulkan-sdk@v1.1.1
        if: ${{inputs.render_api == 'vulkan'}}

      - name: 'Configure Topaz ${{inputs.render_api}}_msvc_${{inputs.build_config}}'
        run: cmake --preset ${{inputs.render_api}}_${{inputs.build_config}}

      - name: 'Build Topaz ${{inputs.render_api}}_msvc_${{inputs.build_config}}'
        run: cmake --build ./build/${{inputs.render_api}}_${{inputs.build_config}} --target topaz
