name: "GCC Code Build"
on:
  workflow_call:
    inputs:
      render_api:
        required: true
        type: string
      build_config:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install necessary linux dependencies
        run:   |
          sudo apt-get install libxrandr-dev libxinerama-dev x11-xkb-utils libxcursor-dev libxi-dev gcc-11 g++-11
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: 'Install Vulkan SDK'
        uses: humbletim/install-vulkan-sdk@v1.1.1
        if: ${{inputs.render_api == 'vulkan'}}

      - name: 'Configure Topaz ${{inputs.render_api}}_gcc_${{inputs.build_config}}'
        run: cmake --preset host_${{inputs.render_api}}_${{inputs.build_config}} -DCMAKE_CXX_COMPILER=g++-11 -DCMAKE_C_COMPILER=gcc-11

      - name: 'Build Topaz ${{inputs.render_api}}_gcc_${{inputs.build_config}}'
        run: cmake --build ./build/${{inputs.render_api}}_${{inputs.build_config}} --target topaz
