name: "GCC Code Build"
on:
  workflow_call:
    inputs:
      render_api:
        required: true
        type: string
      build_config:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install necessary linux dependencies
        run:   |
          sudo apt-get install libxrandr-dev libxinerama-dev x11-xkb-utils libxcursor-dev libxi-dev
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: 'Install Vulkan SDK'
        uses: humbletim/install-vulkan-sdk@v1.1.1
        if: ${{${{inputs.render_api}} == 'vulkan'}}

      - name: 'Build Topaz ${{inputs.render_api}}_gcc_${{inputs.build_config}}'
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: "CMakeListsTxtAdvanced"
          cmakeGenerator: UnixMakefiles
          cmakeAppendedArgs: "-B \"${{github.workspace}}/build/${{inputs.render_api}}_${{inputs.build_config}}\" -DTOPAZ_BUILDCONFIG=${{inputs.build_config}} -DTOPAZ_RENDERAPI=${{inputs.render_api}} -DCMAKE_CXX_COMPILER=g++-10"
          buildWithCmake: true
          buildWithCMakeArgs: "--target topaz --parallel 4"
          buildDirectory: "${{github.workspace}}/build/${{inputs.render_api}}_${{inputs.build_config}}"
