name: "Code Build (OpenGL Debug)"

# Controls when the action will run. 
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gcc_linux:
    uses: Harrand/Topaz/.github/workflows/build_gcc.yml@master
    with:
      render_api: opengl
      build_config: debug

  clang_linux:
    uses: Harrand/Topaz/.github/workflows/build_clang.yml@master
    with:
      render_api: opengl
      build_config: debug

  msvc_windows:
    uses: Harrand/Topaz/.github/workflows/build_msvc.yml@master
    with:
      render_api: opengl
      build_config: debug
