name: "Topaz Code Build"
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  code_build:
    strategy:
      matrix:
        render_api: [vulkan, opengl]
    uses: Harrand/HDK/.github/workflows/hdk.yml@master
      with:
        target: topaz
        preset_prefix: ${{matrix.render_api}}_
    steps:
      - name: 'Linux Dependencies'
        run: |
          sudo apt-get install libxrandr-dev libxinerama-dev x11-xkb-utils libxcursor-dev libxi-dev
        if: runner.os == 'Linux'

      - name: 'Install Vulkan SDK'
        uses: humbletim/install-vulkan-sdk@v1.1.1
        if: ${{matrix.render_api == 'vulkan'}}

