name: "Topaz Code Build"
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  pre_install:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Linux Dependencies'
        run: |
          sudo apt-get install libxrandr-dev libxinerama-dev x11-xkb-utils libxcursor-dev libxi-dev
        if: runner.os == 'Linux'

      - name: 'Install Vulkan SDK'
        uses: humbletim/install-vulkan-sdk@v1.1.1
  code_build:
    needs: pre_install
    strategy:
      matrix:
        render_api: [vulkan, opengl]
    uses: Harrand/HDK/.github/workflows/hdk.yml@master
    with:
      target: topaz
      preset_prefix: ${{matrix.render_api}}_
