name: "Code Build (OpenGL Release)"

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  gcc_linux:
    uses: Harrand/Topaz/.github/workflows/build_gcc.yml@master
    with:
      render_api: opengl
      build_config: release

  clang_linux:
    uses: Harrand/Topaz/.github/workflows/build_clang.yml@master
    with:
      render_api: opengl
      build_config: release

  msvc_windows:
    uses: Harrand/Topaz/.github/workflows/build_msvc.yml@master
    with:
      render_api: opengl
      build_config: release
