name: "Topaz Code Build (OpenGL Debug)"

# Controls when the action will run. 
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup_common:
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

  setup_linux:
    runs-on: ubuntu-latest
    needs: setup_common
    steps:
      - name: Ensure Dependencies
        run:   |
          sudo apt-get install libxrandr-dev libxinerama-dev x11-xkb-utils libxcursor-dev libxi-dev

  gcc_linux:
    runs-on: ubuntu-latest
    needs: setup_linux
    steps:
      - name: 'Build Topaz (ogl_gcc_debug)'
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: "CMakeListsTxtAdvanced"
          cmakeGenerator: UnixMakefiles
          cmakeAppendedArgs: "-B \"${{ github.workspace }}/../../_temp/build/debug\" -DTOPAZ_DEBUG=1 -DTOPAZ_VULKAN=0 -DTOPAZ_OGL=1 -DCMAKE_CXX_COMPILER=g++-10"
          buildWithCMake: true
          buildWithCMakeArgs: "--target topaz --parallel 4"
          buildDirectory: "${{ github.workspace }}/../../_temp/build/debug"

  clang_linux:
    runs-on: ubuntu-latest
    needs: setup_linux
    steps:
      - name: 'Build Topaz (ogl_clang_debug)'
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: "CMakeListsTxtAdvanced"
          cmakeGenerator: UnixMakefiles
          cmakeAppendedArgs: "-B \"${{ github.workspace }}/../../_temp/build/debug\" -DTOPAZ_DEBUG=1 -DTOPAZ_VULKAN=0 -DTOPAZ_OGL=1 -DCMAKE_CXX_COMPILER=clang++-10 -DCMAKE_C_COMPILER=clang-10"
          buildWithCMake: true
          buildWithCMakeArgs: "--target topaz --parallel 4"
          buildDirectory: "${{ github.workspace }}/../../_temp/build/debug"

  msvc_windows:
    runs-on: windows-2022
    needs: setup_common
    steps:
      - name: 'Build Topaz (ogl_msvc_debug)'
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: "CMakeListsTxtAdvanced"
          cmakeGenerator: UnixMakefiles
          cmakeAppendedArgs: "-B \"${{ github.workspace }}/../../_temp/build/debug\" -DTOPAZ_DEBUG=1 -DTOPAZ_VULKAN=0 -DTOPAZ_OGL=1"
          buildWithCMake: true
          buildWithCMakeArgs: "--target tz_triangle_demo --parallel 4"
          buildDirectory: "${{ github.workspace }}/../../_temp/build/debug"
